{ config, lib, pkgs, vars, ... }:

let
  cfg = config.my.hyprland;
  autostartLua = lib.concatMapStringsSep "\n"
    (c: "  hl.exec_cmd(${builtins.toJSON c})") cfg.autostart;
in {
  options.my.hyprland = {
    monitors = lib.mkOption {
      type = lib.types.lines;
      default = "";
      description = "Host-specific Hyprland Lua monitor config.";
    };
    autostart = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [ ];
      description = "Commands to run on hyprland.start.";
    };
    extraConfig = lib.mkOption {
      type = lib.types.lines;
      default = "";
      description = "Extra Lua appended to hyprland.lua.";
    };
  };

  config = {
    programs.hyprland.enable = true;

    environment.sessionVariables = {
      NIXOS_OZONE_WL = "1";
      QT_QPA_PLATFORM = "wayland;xcb";
    };

    home-manager.users.${vars.userName}.xdg.configFile."hypr/hyprland.lua".text = ''
      -- Generated by NixOS (modules/desktop/hyprland.nix). Edit the .nix, not this file.
      local mainMod = "SUPER"

      ${cfg.monitors}

      hl.config({
        general = { gaps_in = 5, gaps_out = 10 },
        input = { kb_layout = "${vars.keyboardLayout}", follow_mouse = 1 },
        misc = { disable_hyprland_logo = true },
        decoration = {
          rounding = 20,
          rounding_power = 2,
          shadow = { enabled = true, range = 4, render_power = 3, color = 0xee1a1a1a },
          blur = { enabled = true, size = 3, passes = 2, vibrancy = 0.1696 },
        },
      })

      hl.on("hyprland.start", function()
      ${autostartLua}
      end)

      -- apps
      hl.bind(mainMod .. " + Return", hl.dsp.exec_cmd("kitty"))
      hl.bind(mainMod .. " + E", hl.dsp.exec_cmd("dolphin"))
      hl.bind(mainMod .. " + Q", hl.dsp.window.close())
      hl.bind(mainMod .. " + SHIFT + M", hl.dsp.exit())
      hl.bind(mainMod .. " + Slash", hl.dsp.exec_cmd("kitty -e sh -c 'hyprctl binds | less'"))

      -- windows
      hl.bind(mainMod .. " + T", hl.dsp.window.float({ action = "toggle" }))

      hl.bind(mainMod .. " + SHIFT + left",  hl.dsp.focus({ direction = "l" }))
      hl.bind(mainMod .. " + SHIFT + right", hl.dsp.focus({ direction = "r" }))
      hl.bind(mainMod .. " + SHIFT + up",    hl.dsp.focus({ direction = "u" }))
      hl.bind(mainMod .. " + SHIFT + down",  hl.dsp.focus({ direction = "d" }))

      hl.bind(mainMod .. " + left",  hl.dsp.window.move({ direction = "l" }))
      hl.bind(mainMod .. " + right", hl.dsp.window.move({ direction = "r" }))
      hl.bind(mainMod .. " + up",    hl.dsp.window.move({ direction = "u" }))
      hl.bind(mainMod .. " + down",  hl.dsp.window.move({ direction = "d" }))

      hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(),   { mouse = true })
      hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

      -- workspaces
      for i = 1, 9 do
        hl.bind(mainMod .. " + " .. i,         hl.dsp.focus({ workspace = tostring(i) }))
        hl.bind(mainMod .. " + SHIFT + " .. i, hl.dsp.window.move({ workspace = tostring(i) }))
      end
      hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
      hl.bind(mainMod .. " + mouse_up",   hl.dsp.focus({ workspace = "e-1" }))

      -- contributed by other modules
      ${cfg.extraConfig}
    '';
  };
}
